name: Permission Scope Demo

on:
  push:

permissions:
  contents: read

jobs:
  read-job:
    runs-on: ubuntu-latest
    steps:
      - name: Read repository
        uses: actions/checkout@v4

      - name: Show read job
        run: echo "Read job succeeded"

  check-repo-details:
    runs-on: ubuntu-latest
    permissions:
       contents: read
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: get repository details
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
         gh api "repos/${{ github.repository }}/issues?state=open"
          --jq '.[] .title'
        
