name: GITHUB_TOKEN Demo

on:
  push:
permissions:
  contents: read
    

jobs:
  token-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show token information
        run: |
          echo "GITHUB_TOKEN exists:"
          if [ -n "${{ github.token }}" ]; then
            echo "YES"
          else
            echo "NO"
          fi